### ISSUE TITLE
Message Sent While Previewing

### ISSUE THREAD

**Issue by toreyhickman** [common-nighthawk/hello-its-me#33]
I recorded a message.  When I was done, the page said that I could preview the message before sending it.  I started previewing my message.  I never saw a button to click to send the message, but eventually the text changed to say that my message was successfully sent.

**Comment by common-nighthawk** [comment]
youre the best, @toreyhickman.

i just wanted to confirm that i got your message.  just in case you were worried this bug killed it.  or if you were worried (which i definitely was) that a 15 minute message wouldnt be supported.

i appreciate the message.  and the bug reports (which ill look into next week).  also--i was feeling pretty unmotivated about this project the last few days, so this was just really really nice.

ill ping you when i respond :)

**Comment by toreyhickman** [comment]
Glad the message sent!  I assumed that it was, but I wasn't sure.

**Comment by common-nighthawk** [comment]
pretty sure this is fixed with all the recent JS updates.  but i didnt specifically test the process of creating a 15 minute message.

will close this issue in a few days/weeks if the problem does not repeat.
